In [0]:
import pandas as pd
import numpy as np


df=pd.DataFrame(np.random.randn(3,3),index=['a','c','e'],columns=['one','two','three'])

In [6]:
df

        one       two     three
a  0.921148 -0.956355 -1.124625
c  1.508716  0.062982  0.064342
e -0.565567  1.190043 -0.585918

In [8]:
df=df.reindex(['a','b','c'])   # index를 바꿔주고 없던 값은 NAN으로 됌
df

        one       two     three
a  0.921148 -0.956355 -1.124625
b       NaN       NaN       NaN
c  1.508716  0.062982  0.064342

In [18]:
df = df.fillna(1)   ### NAN이란 표시를 채워줌
df

        one       two     three
a  0.921148 -0.956355 -1.124625
b  1.000000  1.000000  1.000000
c  1.508716  0.062982  0.064342

In [53]:
df4=pd.DataFrame(np.random.randn(5,3),index=['a','c','e','f','h'],columns=['one','two','three'])
df4

        one       two     three
a -0.776736 -0.574449  0.496488
c  2.042395  0.583461 -0.708742
e  1.239813  1.494271 -0.086830
f -0.990431  0.250552  0.618397
h  0.347696 -0.259946 -0.225211

In [54]:
df4=df4.reindex(['a','b','c','d','e','f','g','h'])
df4

        one       two     three
a -0.776736 -0.574449  0.496488
b       NaN       NaN       NaN
c  2.042395  0.583461 -0.708742
d       NaN       NaN       NaN
e  1.239813  1.494271 -0.086830
f -0.990431  0.250552  0.618397
g       NaN       NaN       NaN
h  0.347696 -0.259946 -0.225211

In [56]:
df4.dropna(axis=0)        # nan인거 다 drop

        one       two     three
a -0.776736 -0.574449  0.496488
c  2.042395  0.583461 -0.708742
e  1.239813  1.494271 -0.086830
f -0.990431  0.250552  0.618397
h  0.347696 -0.259946 -0.225211

In [39]:
df=pd.DataFrame({'one':[10,20,30,40,50,2000],'two':[1000,0,30,40,50,60]})
df

    one   two
0    10  1000
1    20     0
2    30    30
3    40    40
4    50    50
5  2000    60

In [51]:
df2=df.replace({1000:10,2000:60})  # 바꾸기
df2

   one  two
0   10   10
1   20    0
2   30   30
3   40   40
4   50   50
5   60   60

In [45]:
data={'Price':['2500000','2700000'],'Value':['21','84']}
df1=pd.DataFrame(data)
df1

     Price Value
0  2500000    21
1  2700000    84

In [46]:
df1=df1.astype(float)   #형태 설정
df1

       Price  Value
0  2500000.0   21.0
1  2700000.0   84.0